[build-system]
build-backend = "uv_build"
requires = ["uv_build"]

[project]
dependencies = []
description = "Add your description here"
name = "biped-assets"
requires-python = ">=3.10"
version = "0.1.0"

[tool.uv.build-backend]
module-root = ""
