controller:
  mode_pr: PR                 # PR ou AB (pour les chevilles)
  mode_machine: inherit       # "inherit" (depuis lowstate) ou un entier (ex: 0)
  control_dt: 0.002           # 2 ms => 500 Hz
  ramp_to_zero_duration: 2.0  # secondes pour ramener les consignes a zero


joints:
- name: left_hip_yaw_joint
  kp: 200.0
  kd: 2.5
  enabled: true
- name: left_hip_pitch_joint
  kp: 200.0
  kd: 2.5
  enabled: true
- name: left_hip_roll_joint
  kp: 200.0
  kd: 2.5
  enabled: true
- name: left_knee_joint
  kp: 300.0
  kd: 4.0
  enabled: true
- name: left_ankle_pitch_joint
  kp: 40.0
  kd: 2.0
  enabled: true
- name: left_ankle_roll_joint
  kp: 40.0
  kd: 2.0
  enabled: true
- name: right_hip_yaw_joint
  kp: 200.0
  kd: 2.5
  enabled: true
- name: right_hip_pitch_joint
  kp: 200.0
  kd: 2.5
  enabled: true
- name: right_hip_roll_joint
  kp: 200.0
  kd: 2.5
  enabled: true
- name: right_knee_joint
  kp: 300.0
  kd: 4.0
  enabled: true
- name: right_ankle_pitch_joint
  kp: 40.0
  kd: 2.0
  enabled: true
- name: right_ankle_roll_joint
  kp: 40.0
  kd: 2.0
  enabled: true
- name: torso_joint
  kp: 300.0
  kd: 3.0
  enabled: false
- name: left_shoulder_pitch_joint
  kp: 120.0
  kd: 2.0
  enabled: false
- name: left_shoulder_roll_joint
  kp: 120.0
  kd: 2.0
  enabled: false
- name: left_shoulder_yaw_joint
  kp: 120.0
  kd: 2.0
  enabled: false
- name: left_elbow_joint
  kp: 80.0
  kd: 1.0
  enabled: false
- name: left_wrist_roll_joint
  kp: 80.0
  kd: 1.0
  enabled: false
- name: left_wrist_pitch_joint
  kp: 80.0
  kd: 1.0
  enabled: false
- name: left_wrist_yaw_joint
  kp: 80.0
  kd: 1.0
  enabled: false
- name: right_shoulder_pitch_joint
  kp: 120.0
  kd: 2.0
  enabled: false
- name: right_shoulder_roll_joint
  kp: 120.0
  kd: 2.0
  enabled: false
- name: right_shoulder_yaw_joint
  kp: 120.0
  kd: 2.0
  enabled: false
- name: right_elbow_joint
  kp: 80.0
  kd: 1.0
  enabled: false
- name: right_wrist_roll_joint
  kp: 80.0
  kd: 1.0
  enabled: false
- name: right_wrist_pitch_joint
  kp: 80.0
  kd: 1.0
  enabled: false
- name: right_wrist_yaw_joint
  kp: 80.0
  kd: 1.0
  enabled: false