# ==============================================================================
#           FICHIER DE CONFIGURATION DES POIDS SUR LA TRAJECTOIRE

#     Modifiez les valeurs ci-dessous. Un poids de 0.0 désactive la contrainte.
# ==============================================================================

# Description de cette configuration pour s'en souvenir.
description: "Fichier de configuration pour le squat."

# --- WEIGH ON CONFIGURATION q (size is 3 + 3 + 27 = 33) ---
q_weights:
  # Poids sur la Position de la Base (x, y, z)
  - 0.1 # [q 0] base_pos_x
  - 0.1 # [q 1] base_pos_y
  - 5.0 # [q 2] base_pos_z

  # Poids sur l'Orientation de la Base (rot_x, rot_y, rot_z)
  - 1.0 # [q 3] base_orientation_x
  - 1.0 # [q 4] base_orientation_y
  - 1.0 # [q 5] base_orientation_z

  # Weight on joint positions (27)
  - 1.0 # [q 6]  Pos of left_hip_yaw_joint
  - 1.0 # [q 7]  Pos of left_hip_pitch_joint
  - 1.0 # [q 8]  Pos of left_hip_roll_joint
  - 1.0 # [q 9]  Pos of left_knee_joint
  - 1.0 # [q 10] Pos of left_ankle_pitch_joint
  - 1.0 # [q 11] Pos of left_ankle_roll_joint

  - 1.0 # [q 12] Pos of right_hip_yaw_joint
  - 1.0 # [q 13] Pos of right_hip_pitch_joint
  - 1.0 # [q 14] Pos of right_hip_roll_joint
  - 1.0 # [q 15] Pos of right_knee_joint
  - 1.0 # [q 16] Pos of right_ankle_pitch_joint
  - 1.0 # [q 17] Pos of right_ankle_roll_joint

  - 5.0 # [q 18] Pos of torso_joint

  - 1.0 # [q 19] Pos of left_shoulder_pitch_joint
  - 1.0 # [q 20] Pos of left_shoulder_roll_joint
  - 1.0 # [q 21] Pos of left_shoulder_yaw_joint
  - 1.0 # [q 22] Pos of left_elbow_joint
  - 1.0 # [q 23] Pos of left_wrist_roll_joint
  - 1.0 # [q 24] Pos of left_wrist_pitch_joint
  - 1.0 # [q 25] Pos of left_wrist_yaw_joint

  - 1.0 # [q 26] Pos of right_shoulder_pitch_joint
  - 1.0 # [q 27] Pos of right_shoulder_roll_joint
  - 1.0 # [q 28] Pos of right_shoulder_yaw_joint
  - 1.0 # [q 29] Pos of right_elbow_joint
  - 1.0 # [q 30] Pos of right_wrist_roll_joint
  - 1.0 # [q 31] Pos of right_wrist_pitch_joint
  - 1.0 # [q 32] Pos of right_wrist_yaw_joint


# --- WEIGHT ON SPEED (size 3 + 3 + 27 = 33) ---
v_weights:
  # Weight on base linear velocity (vx, vy, vz)
  - 0.1 # [v 0] base_lin_vel_x
  - 0.1 # [v 1] base_lin_vel_y
  - 0.1 # [v 2] base_lin_vel_z

  # Weight on base angular velocity (wx, wy, wz)
  - 0.1 # [v 3] base_ang_vel_x
  - 0.1 # [v 4] base_ang_vel_y
  - 0.1 # [v 5] base_ang_vel_z

  # Weight on joint velocities (27)
  - 0.1 # [v 6]  Pos of left_hip_yaw_joint
  - 0.1 # [v 7]  Pos of left_hip_pitch_joint
  - 0.1 # [v 8]  Pos of left_hip_roll_joint
  - 0.1 # [v 9]  Pos of left_knee_joint
  - 0.1 # [v 10] Pos of left_ankle_pitch_joint
  - 0.1 # [v 11] Pos of left_ankle_roll_joint

  - 0.1 # [v 12] Pos of right_hip_yaw_joint
  - 0.1 # [v 13] Pos of right_hip_pitch_joint
  - 0.1 # [v 14] Pos of right_hip_roll_joint
  - 0.1 # [v 15] Pos of right_knee_joint
  - 0.1 # [v 16] Pos of right_ankle_pitch_joint
  - 0.1 # [v 17] Pos of right_ankle_roll_joint

  - 0.1 # [v 18] Pos of torso_joint

  - 0.1 # [v 19] Pos of left_shoulder_pitch_joint
  - 0.1 # [v 20] Pos of left_shoulder_roll_joint
  - 0.1 # [v 21] Pos of left_shoulder_yaw_joint
  - 0.1 # [v 22] Pos of left_elbow_joint
  - 0.1 # [v 23] Pos of left_wrist_roll_joint
  - 0.1 # [v 24] Pos of left_wrist_pitch_joint
  - 0.1 # [v 25] Pos of left_wrist_yaw_joint

  - 0.1 # [v 26] Pos of right_shoulder_pitch_joint
  - 0.1 # [v 27] Pos of right_shoulder_roll_joint
  - 0.1 # [v 28] Pos of right_shoulder_yaw_joint
  - 0.1 # [v 29] Pos of right_elbow_joint
  - 0.1 # [v 30] Pos of right_wrist_roll_joint
  - 0.1 # [v 31] Pos of right_wrist_pitch_joint
  - 0.1 # [v 32] Pos of right_wrist_yaw_joint